import { Event } from '@/types';

export const seedEvents: Event[] = [
  {
    id: '1',
    title: 'AI & Machine Learning Summit 2026',
    category: 'conference',
    date: '2026-03-15',
    time: '09:00 AM',
    location: 'San Francisco, CA',
    venue: 'Moscone Center, Hall A',
    description: 'Join industry leaders to explore the latest in AI and ML technologies.',
    fullDescription: 'The AI & Machine Learning Summit brings together thought leaders, researchers, and practitioners from around the world. Explore cutting-edge developments in artificial intelligence, deep learning, neural networks, and practical ML applications. Features keynote speeches, hands-on workshops, and networking opportunities with leading tech companies.',
    totalSeats: 500,
    bookedSeats: 342,
    image: 'https://images.unsplash.com/photo-1591453089816-0fbb971b454c?w=800&h=500&fit=crop',
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Web Development Masterclass',
    category: 'workshop',
    date: '2026-03-20',
    time: '02:00 PM',
    location: 'Online',
    venue: 'Virtual Classroom via Zoom',
    description: 'Learn modern web development from React to full-stack deployment.',
    fullDescription: 'Dive deep into modern web development practices with this comprehensive masterclass. Cover React, TypeScript, state management, API integration, authentication, deployment strategies, and performance optimization. Includes hands-on coding exercises, real-world project examples, and lifetime access to course materials.',
    totalSeats: 100,
    bookedSeats: 87,
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=500&fit=crop',
    createdAt: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Startup Pitch Night',
    category: 'networking',
    date: '2026-03-22',
    time: '06:00 PM',
    location: 'New York, NY',
    venue: 'Innovation Hub, 5th Floor',
    description: 'Connect with investors, founders, and entrepreneurs in a dynamic setting.',
    fullDescription: 'An evening dedicated to innovation and entrepreneurship. Watch promising startups pitch their ideas to a panel of experienced investors and VCs. Network with fellow entrepreneurs, share insights, and discover potential collaboration opportunities. Includes cocktail reception and one-on-one mentor sessions.',
    totalSeats: 150,
    bookedSeats: 95,
    image: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=800&h=500&fit=crop',
    createdAt: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'UX Design Principles Webinar',
    category: 'webinar',
    date: '2026-03-25',
    time: '11:00 AM',
    location: 'Online',
    venue: 'Google Meet Conference Room',
    description: 'Master the fundamentals of user experience and interface design.',
    fullDescription: 'Explore core UX design principles with industry experts from leading design agencies. Learn about user research, wireframing, prototyping, usability testing, and design systems. Perfect for designers, product managers, and developers looking to enhance their UX skills. Includes live Q&A and downloadable resources.',
    totalSeats: 200,
    bookedSeats: 178,
    image: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=800&h=500&fit=crop',
    createdAt: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'Cloud Computing Conference',
    category: 'conference',
    date: '2026-04-10',
    time: '10:00 AM',
    location: 'Seattle, WA',
    venue: 'Washington State Convention Center',
    description: 'Explore cloud architecture, serverless, and modern DevOps practices.',
    fullDescription: 'The premier cloud computing event featuring sessions on AWS, Azure, Google Cloud, microservices architecture, Kubernetes, serverless computing, and cloud security. Network with cloud architects, DevOps engineers, and CTOs from Fortune 500 companies. Includes certification workshops and hands-on labs.',
    totalSeats: 600,
    bookedSeats: 412,
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&h=500&fit=crop',
    createdAt: new Date().toISOString(),
  },
  {
    id: '6',
    title: 'Mobile App Development Workshop',
    category: 'workshop',
    date: '2026-04-18',
    time: '01:00 PM',
    location: 'Austin, TX',
    venue: 'Tech Hub Austin, Room 301',
    description: 'Build cross-platform mobile apps with React Native and Flutter.',
    fullDescription: 'Hands-on workshop teaching you how to build beautiful, performant mobile applications for iOS and Android. Cover React Native fundamentals, state management, navigation, API integration, push notifications, and app store deployment. Bring your laptop and leave with a working mobile app.',
    totalSeats: 50,
    bookedSeats: 43,
    image: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=500&fit=crop',
    createdAt: new Date().toISOString(),
  },
  {
    id: '7',
    title: 'Blockchain & Crypto Meetup',
    category: 'networking',
    date: '2026-04-25',
    time: '07:00 PM',
    location: 'Miami, FL',
    venue: 'Blockchain Center Miami',
    description: 'Network with blockchain developers, investors, and crypto enthusiasts.',
    fullDescription: 'Join the vibrant blockchain community for an evening of knowledge sharing and networking. Discuss DeFi, NFTs, smart contracts, Web3 development, and cryptocurrency trends. Features lightning talks, panel discussions, and plenty of time to connect with fellow blockchain enthusiasts and industry leaders.',
    totalSeats: 120,
    bookedSeats: 18,
    image: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&h=500&fit=crop',
    createdAt: new Date().toISOString(),
  },
  {
    id: '8',
    title: 'Cybersecurity Best Practices',
    category: 'webinar',
    date: '2026-05-05',
    time: '03:00 PM',
    location: 'Online',
    venue: 'Microsoft Teams Live Event',
    description: 'Learn essential cybersecurity strategies to protect your organization.',
    fullDescription: 'Comprehensive webinar covering modern cybersecurity threats and defense strategies. Topics include zero-trust architecture, penetration testing, incident response, security automation, compliance frameworks, and employee security training. Led by certified security professionals with real-world case studies.',
    totalSeats: 300,
    bookedSeats: 6,
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&h=500&fit=crop',
    createdAt: new Date().toISOString(),
  },
];
